import type { CatalogProduct } from "@/types/catalog";

import { buildCoverArt } from "./helpers";

export const FALLBACK_PRODUCTS: CatalogProduct[] = [
  {
    id: "sirah-ringkas",
    slug: "sirah-ringkas-nabi",
    title: "Sirah Ringkas Nabi",
    category: "Sirah & Sejarah",
    originalPrice: 79000,
    finalPrice: 69000,
    discountPercent: 13,
    imageUrl: buildCoverArt("Sirah Ringkas Nabi", "#2E7D32", "#F57C00"),
    description:
      "Menyajikan kisah perjuangan Rasulullah dengan bahasa yang hangat dan mudah dipahami keluarga.",
    detailUrl: "/produk/sirah-ringkas-nabi",
    stock: 120,
    weight: 680,
    preorder: false,
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "adab-harian",
    slug: "adab-harian-muslim",
    title: "Adab Harian Muslim",
    category: "Akhlak & Adab",
    originalPrice: 65000,
    finalPrice: 59000,
    discountPercent: 9,
    imageUrl: buildCoverArt("Adab Harian Muslim", "#1B5E20", "#FF8F00"),
    description:
      "Panduan praktis membangun adab dari rumah hingga ruang belajar dengan contoh konkret.",
    detailUrl: "/produk/adab-harian-muslim",
    stock: 160,
    weight: 600,
    preorder: false,
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "tafsir-familia",
    slug: "tafsir-untuk-keluarga",
    title: "Tafsir Untuk Keluarga",
    category: "Tafsir",
    originalPrice: 125000,
    finalPrice: 102000,
    discountPercent: 18,
    imageUrl: buildCoverArt("Tafsir Untuk Keluarga", "#33691E", "#FB8C00"),
    description:
      "Ringkas, sistematis, dan disusun untuk membantu pembaca memahami pesan ayat secara aplikatif.",
    detailUrl: "/produk/tafsir-untuk-keluarga",
    stock: 243,
    weight: 610,
    preorder: false,
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "fiqih-ibadah",
    slug: "fiqih-ibadah-praktis",
    title: "Fiqih Ibadah Praktis",
    category: "Fiqih",
    originalPrice: 98000,
    finalPrice: 91000,
    discountPercent: 7,
    imageUrl: buildCoverArt("Fiqih Ibadah Praktis", "#2E7D32", "#F9A825"),
    description:
      "Didesain untuk mempermudah pembaca mempraktikkan ibadah dengan tenang dan yakin.",
    detailUrl: "/produk/fiqih-ibadah-praktis",
    stock: 84,
    weight: 560,
    preorder: false,
    isBestSeller: false,
    isFeatured: true,
  },
  {
    id: "quran-hadits",
    slug: "quran-hadits-anak",
    title: "Qur'an & Hadits Anak",
    category: "Anak & Remaja",
    originalPrice: 72000,
    finalPrice: 72000,
    discountPercent: 0,
    imageUrl: buildCoverArt("Qur'an & Hadits Anak", "#388E3C", "#EF6C00"),
    description:
      "Format visual ringan untuk mengenalkan nilai Qur'an dan Hadits sejak usia dini.",
    detailUrl: "/produk/quran-hadits-anak",
    stock: 98,
    weight: 550,
    preorder: false,
    isBestSeller: false,
    isFeatured: false,
  },
  {
    id: "ramadhan-kreatif",
    slug: "ramadhan-lebih-bermakna",
    title: "Ramadhan Lebih Bermakna",
    category: "Ramadhan",
    originalPrice: 55000,
    finalPrice: 55000,
    discountPercent: 0,
    imageUrl: buildCoverArt("Ramadhan Lebih Bermakna", "#1E88E5", "#FB8C00"),
    description:
      "Ide kegiatan dan refleksi harian untuk menghidupkan Ramadhan di rumah dan komunitas.",
    detailUrl: "/produk/ramadhan-lebih-bermakna",
    stock: 73,
    weight: 600,
    preorder: false,
    isBestSeller: false,
    isFeatured: false,
  },
  {
    id: "doa-sehari-hari",
    slug: "doa-sehari-hari",
    title: "Doa Sehari-hari",
    category: "Doa & Dzikir",
    originalPrice: 45000,
    finalPrice: 45000,
    discountPercent: 0,
    imageUrl: buildCoverArt("Doa Sehari-hari", "#2E7D32", "#FFA726"),
    description:
      "Koleksi doa ringkas yang mudah dihafal, cocok untuk keluarga dan pembelajaran dasar.",
    detailUrl: "/produk/doa-sehari-hari",
    stock: 105,
    weight: 500,
    preorder: false,
    isBestSeller: false,
    isFeatured: false,
  },
  {
    id: "bisnis-halal",
    slug: "bisnis-halal-berkah",
    title: "Bisnis Halal Berkah",
    category: "Ekonomi Syariah",
    originalPrice: 138000,
    finalPrice: 129000,
    discountPercent: 7,
    imageUrl: buildCoverArt("Bisnis Halal Berkah", "#1B5E20", "#F57C00"),
    description:
      "Membantu pembaca membangun usaha yang beretika, rapi, dan selaras dengan nilai syariah.",
    detailUrl: "/produk/bisnis-halal-berkah",
    stock: 67,
    weight: 920,
    preorder: false,
    isBestSeller: true,
    isFeatured: true,
  },
];
